[tool.poetry]
name = "DisnakeBot"
version = "1.0.0"
description = "An example music bot written in disnake and wavelink"
authors = ["KortaPo"]

[tool.poetry.dependencies]
python = "^3.8"
aiodns = "3.0.0"
aiohttp = "3.7.4.post0"
anyio = "3.3.1"
astunparse = "1.6.3"
async-timeout = "3.0.1"
attrs = "21.2.0"
braceexpand = "0.1.7"
Brotli = "1.0.9"
cchardet = "2.1.7"
certifi = "2021.5.30"
cffi = "1.14.6"
chardet = "4.0.0"
charset-normalizer = "2.0.5"
click = "8.0.1"
h11 = "0.12.0"
httpcore = "0.13.7"
httpx = "0.19.0"
humanize = "3.11.0"
idna = "3.2"
import-expression = "1.1.4"
multidict = "5.1.0"
disnake = {version = "2.1.2", extras = ["discord"]}
orjson = "3.6.3"
pycares = "4.0.0"
pycparser = "2.20"
PyNaCl = "1.4.0"
rfc3986 = "1.5.0"
six = "1.16.0"
sniffio = "1.2.0"
typing-extensions = "3.10.0.2"
yarl = "1.6.3"
youtube_dl = "2021.6.6"
youtube-search-python = "1.4.7"
wavelink = "^0.9.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
